services:

  myapp:
    image: myapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    links:
      - mysql_db:mysql_db
    environment:
      - spring.datasource.url=jdbc:mysql://mysql_db:3306/myappdata?allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    restart: always
    ports:
      - 8080:8080

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: myappdata
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./src/main/resources/sql-files/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/main/resources/sql-files/1.txt:/var/lib/mysql-files/1.txt
      - ./src/main/resources/sql-files/2.txt:/var/lib/mysql-files/2.txt
      - ./src/main/resources/sql-files/3.txt:/var/lib/mysql-files/3.txt
    restart: always
    ports: 
      - 3306:3306 
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=""
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55